import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vamos
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    static List<Item> items;
    List<Item> listOfHaz;
    List<Item> listOfTap;
    List<Item> listOfProcesszor;
    List<Item> listOfAlaplap;
    List<Item> listOfSsd;
    
    static InputOutput ioput;
    static Basket myBasket;
    static DefaultListModel myModel1;
    static DefaultListModel myModel2;
    static DefaultListModel myModel3;
    static DefaultListModel myModel4;
    static DefaultListModel myModel5;
    static DefaultListModel basketmodel = new DefaultListModel();
    
    public MainFrame() {
        
        initComponents();
        loadSubList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        hozzaadHazButton = new javax.swing.JButton();
        hozzaadTapButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hozzaadProcesszorButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        hozzaadAlaplapButton = new javax.swing.JButton();
        hozzaadSsdButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        rendezHazButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList<>();
        rendezTapButton = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList8 = new javax.swing.JList<>();
        rendezProcesszorButton = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList9 = new javax.swing.JList<>();
        rendezAlaplapButton = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList10 = new javax.swing.JList<>();
        rendezSsdButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Webshopunk kínálata");
        setBackground(new java.awt.Color(255, 255, 255));

        jList3.setModel(myModel3);
        jScrollPane1.setViewportView(jList3);

        jList2.setModel(myModel2);
        jScrollPane2.setViewportView(jList2);

        hozzaadHazButton.setText("Hozzáadás");
        hozzaadHazButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hozzaadHazButtonActionPerformed(evt);
            }
        });

        hozzaadTapButton.setText("Hozzáadás");
        hozzaadTapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hozzaadTapButtonActionPerformed(evt);
            }
        });

        jList1.setModel(myModel1);
        jScrollPane3.setViewportView(jList1);

        jLabel1.setText("Ház");

        jLabel2.setText("Tápegység");

        jLabel3.setText("Processzor");

        jLabel4.setText("Alaplap");

        hozzaadProcesszorButton.setText("Hozzáadás");
        hozzaadProcesszorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hozzaadProcesszorButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("SSD");

        jList4.setModel(myModel4);
        jScrollPane4.setViewportView(jList4);

        hozzaadAlaplapButton.setText("Hozzáadás");
        hozzaadAlaplapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hozzaadAlaplapButtonActionPerformed(evt);
            }
        });

        hozzaadSsdButton.setText("Hozzáadás");
        hozzaadSsdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hozzaadSsdButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PC Varázs Webshop");
        jLabel7.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jList5.setModel(myModel5);
        jScrollPane5.setViewportView(jList5);

        jList6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ár", "Típus" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jList6);

        rendezHazButton.setText("Rendezés");
        rendezHazButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rendezHazButtonActionPerformed(evt);
            }
        });

        jList7.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ár", "Típus" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList7);

        rendezTapButton.setText("Rendezés");
        rendezTapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rendezTapButtonActionPerformed(evt);
            }
        });

        jList8.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ár", "Típus" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(jList8);

        rendezProcesszorButton.setText("Rendezés");
        rendezProcesszorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rendezProcesszorButtonActionPerformed(evt);
            }
        });

        jList9.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ár", "Típus" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(jList9);

        rendezAlaplapButton.setText("Rendezés");
        rendezAlaplapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rendezAlaplapButtonActionPerformed(evt);
            }
        });

        jList10.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ár", "Típus" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(jList10);

        rendezSsdButton.setText("Rendezés");
        rendezSsdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rendezSsdButtonActionPerformed(evt);
            }
        });

        jButton7.setText("Kosár megtekintése");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(hozzaadTapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hozzaadHazButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rendezHazButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rendezTapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane8)
                                .addComponent(hozzaadProcesszorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rendezProcesszorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hozzaadSsdButton)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hozzaadAlaplapButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rendezAlaplapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane10)
                                    .addComponent(rendezSsdButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hozzaadHazButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rendezHazButton))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hozzaadTapButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rendezTapButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hozzaadProcesszorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rendezProcesszorButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hozzaadAlaplapButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rendezAlaplapButton)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hozzaadSsdButton)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rendezSsdButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jButton7)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadSubList(){
        listOfHaz = new ArrayList();
        listOfTap = new ArrayList();
        listOfProcesszor = new ArrayList();
        listOfAlaplap = new ArrayList();
        listOfSsd = new ArrayList();
        
        for(int i=0; i<items.size(); i++){
            String currentItemName = items.get(i).getName(); 
            
            switch(currentItemName){
                case "ház": listOfHaz.add(items.get(i)); break; 
                case "tápegység": listOfTap.add(items.get(i)); break;
                case "processzor": listOfProcesszor.add(items.get(i)); break;
                case "alaplap": listOfAlaplap.add(items.get(i)); break;
                case "ssd": listOfSsd.add(items.get(i)); break;
            }
        }
    }
    
    private void hozzaadHazButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hozzaadHazButtonActionPerformed
        // TODO add your handling code here:        
        if(!jList1.isSelectionEmpty()){
            int selectedIndex = jList1.getSelectedIndex();
            myBasket.addToBasket(listOfHaz.get(selectedIndex));
        }        
    }//GEN-LAST:event_hozzaadHazButtonActionPerformed

    private void rendezHazButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rendezHazButtonActionPerformed
        // TODO add your handling code here:        
        int indexOfSorter = jList6.getSelectedIndex();
       
        switch(indexOfSorter){
            case 0: listOfHaz.sort(Comparator.comparing(Item::getPrice));break;
            case 1: listOfHaz.sort(Comparator.comparing(Item::getType));break;
        }    
       
        myModel1.clear();
        
        for(int i=0; i<listOfHaz.size(); i++){
            myModel1.addElement(listOfHaz.get(i).toList());
        }
        
        jList1.setModel(myModel1);
    }//GEN-LAST:event_rendezHazButtonActionPerformed

    private void rendezTapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rendezTapButtonActionPerformed
        // TODO add your handling code here:
        int indexOfSorter = jList7.getSelectedIndex();
        
        switch(indexOfSorter){
            case 0: listOfTap.sort(Comparator.comparing(Item::getPrice));break;
            case 1: listOfTap.sort(Comparator.comparing(Item::getType));break;
        }
        
        myModel2.clear();
        
        for(int i=0; i<listOfTap.size(); i++){
            myModel2.addElement(listOfTap.get(i).toList());
        }
        
        jList2.setModel(myModel2);
    }//GEN-LAST:event_rendezTapButtonActionPerformed

    private void rendezProcesszorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rendezProcesszorButtonActionPerformed
        // TODO add your handling code here:
        int indexOfSorter = jList8.getSelectedIndex();
        
        switch(indexOfSorter){
            case 0: listOfProcesszor.sort(Comparator.comparing(Item::getPrice));break;
            case 1: listOfProcesszor.sort(Comparator.comparing(Item::getType));break;
        }
        
        myModel3.clear();
        
        for(int i=0; i<listOfProcesszor.size(); i++){
            myModel3.addElement(listOfProcesszor.get(i).toList());
        }
        
        jList3.setModel(myModel3);
    }//GEN-LAST:event_rendezProcesszorButtonActionPerformed

    private void rendezAlaplapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rendezAlaplapButtonActionPerformed
        // TODO add your handling code here:
        int indexOfSorter = jList9.getSelectedIndex();
        
        switch(indexOfSorter){
            case 0: listOfAlaplap.sort(Comparator.comparing(Item::getPrice));break;
            case 1: listOfAlaplap.sort(Comparator.comparing(Item::getType));break;
        }
        
        myModel4.clear();
        
        for(int i=0; i<listOfAlaplap.size(); i++){
            myModel4.addElement(listOfAlaplap.get(i).toList());
        }
        
        jList4.setModel(myModel4);
    }//GEN-LAST:event_rendezAlaplapButtonActionPerformed

    private void rendezSsdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rendezSsdButtonActionPerformed
        // TODO add your handling code here:
        int indexOfSorter = jList10.getSelectedIndex();
        
        switch(indexOfSorter){
            case 0: listOfSsd.sort(Comparator.comparing(Item::getPrice));break;
            case 1: listOfSsd.sort(Comparator.comparing(Item::getType));break;
        }
        
        myModel5.clear();
        
        for(int i=0; i<listOfSsd.size(); i++){
            myModel5.addElement(listOfSsd.get(i).toList());
        }
        
        jList5.setModel(myModel5);
    }//GEN-LAST:event_rendezSsdButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        for(int i=0; i<myBasket.getBasketSize(); i++){
            basketmodel.addElement(myBasket.getAnItem(myBasket, i).toString());
        }
        BasketFrame secondFrame = new BasketFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasketFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton7ActionPerformed

    private void hozzaadAlaplapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hozzaadAlaplapButtonActionPerformed
        // TODO add your handling code here:
        if(!jList4.isSelectionEmpty()){
            int selectedIndex = jList4.getSelectedIndex();
            myBasket.addToBasket(listOfAlaplap.get(selectedIndex));
        }
    }//GEN-LAST:event_hozzaadAlaplapButtonActionPerformed

    private void hozzaadTapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hozzaadTapButtonActionPerformed
        // TODO add your handling code here:   
        if(!jList2.isSelectionEmpty()){
            int selectedIndex = jList2.getSelectedIndex();
            myBasket.addToBasket(listOfTap.get(selectedIndex));
        }
    }//GEN-LAST:event_hozzaadTapButtonActionPerformed

    private void hozzaadProcesszorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hozzaadProcesszorButtonActionPerformed
        // TODO add your handling code here:      
        if(!jList3.isSelectionEmpty()){
            int selectedIndex = jList3.getSelectedIndex();
            myBasket.addToBasket(listOfProcesszor.get(selectedIndex));
        }
    }//GEN-LAST:event_hozzaadProcesszorButtonActionPerformed

    private void hozzaadSsdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hozzaadSsdButtonActionPerformed
        // TODO add your handling code here:   
        if(!jList5.isSelectionEmpty()){
            int selectedIndex = jList5.getSelectedIndex();
            myBasket.addToBasket(listOfSsd.get(selectedIndex));
        }
    }//GEN-LAST:event_hozzaadSsdButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
        
        items = new ArrayList();
        ioput = new InputOutput();
        myBasket = new Basket();
        items = ioput.readItems();
        
        int numOfHaz = 0, numOfTapegyseg = 0, numOfProcesszor = 0, numOfAlaplap = 0, numOfSsd = 0;
        
        myModel1 = new DefaultListModel();
        myModel2 = new DefaultListModel();
        myModel3 = new DefaultListModel();
        myModel4 = new DefaultListModel();
        myModel5 = new DefaultListModel();
        for(int i=0; i<items.size(); i++){
            switch(items.get(i).getName()){
                case "ház": myModel1.addElement(items.get(i).toList()); numOfHaz++; break;
                case "tápegység": myModel2.addElement(items.get(i).toList()); numOfTapegyseg++; break;
                case "processzor": myModel3.addElement(items.get(i).toList()); numOfProcesszor++; break;
                case "alaplap": myModel4.addElement(items.get(i).toList()); numOfAlaplap++; break;
                case "ssd": myModel5.addElement(items.get(i).toList()); numOfSsd++; break;
            }
        }   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hozzaadAlaplapButton;
    private javax.swing.JButton hozzaadHazButton;
    private javax.swing.JButton hozzaadProcesszorButton;
    private javax.swing.JButton hozzaadSsdButton;
    private javax.swing.JButton hozzaadTapButton;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList10;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList6;
    private javax.swing.JList<String> jList7;
    private javax.swing.JList<String> jList8;
    private javax.swing.JList<String> jList9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton rendezAlaplapButton;
    private javax.swing.JButton rendezHazButton;
    private javax.swing.JButton rendezProcesszorButton;
    private javax.swing.JButton rendezSsdButton;
    private javax.swing.JButton rendezTapButton;
    // End of variables declaration//GEN-END:variables
}
